@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":PlannerParser" as PlannerParser LOGIC_COLOR
participant ":StudentCommandParser" as StudentCommandParser LOGIC_COLOR
participant ":StudentRemoveCommandParser" as StudentRemoveCommandParser LOGIC_COLOR
participant "d:StudentRemoveCommand" as StudentRemoveCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("student remove 1")
activate LogicManager

LogicManager -> PlannerParser : parseCommand("student remove 1")
activate PlannerParser

create StudentCommandParser
PlannerParser -> StudentCommandParser
activate StudentCommandParser

StudentCommandParser --> PlannerParser
deactivate StudentCommandParser

PlannerParser -> StudentCommandParser : parse("remove 1")
activate StudentCommandParser

create StudentRemoveCommandParser
StudentCommandParser --> StudentRemoveCommandParser
activate StudentRemoveCommandParser

StudentRemoveCommandParser --> StudentCommandParser
deactivate StudentRemoveCommandParser

StudentCommandParser -> StudentRemoveCommandParser : parse("1")
activate StudentRemoveCommandParser

create StudentRemoveCommand
StudentRemoveCommandParser -> StudentRemoveCommand
activate StudentRemoveCommand

StudentRemoveCommand --> StudentRemoveCommandParser : d
deactivate StudentRemoveCommand

StudentRemoveCommandParser --> StudentCommandParser : d
deactivate StudentRemoveCommandParser

StudentCommandParser --> PlannerParser : d
deactivate StudentCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
StudentCommandParser -[hidden]-> PlannerParser
destroy StudentCommandParser

PlannerParser --> LogicManager : d
deactivate PlannerParser

LogicManager -> StudentRemoveCommand : execute()
activate StudentRemoveCommand

StudentRemoveCommand -> Model : deleteStudent(1)
activate Model

Model --> StudentRemoveCommand
deactivate Model

create CommandResult
StudentRemoveCommand -> CommandResult
activate CommandResult

CommandResult --> StudentRemoveCommand
deactivate CommandResult

StudentRemoveCommand --> LogicManager : result
deactivate StudentRemoveCommand

[<--LogicManager
deactivate LogicManager
@enduml
