@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":PlannerParser" as PlannerParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedPlanner" as VersionedPlanner MODEL_COLOR
end box
[-> LogicManager : execute("undo")
activate LogicManager

LogicManager -> PlannerParser : parseCommand("undo")
activate PlannerParser

create UndoCommand
PlannerParser -> UndoCommand
activate UndoCommand

UndoCommand --> PlannerParser
deactivate UndoCommand

PlannerParser --> LogicManager : u
deactivate PlannerParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoPlanner()
activate Model

Model -> VersionedPlanner : undo()
activate VersionedPlanner

VersionedPlanner -> VersionedPlanner :resetData(ReadOnlyPlanner)
VersionedPlanner --> Model :
deactivate VersionedPlanner

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
