= NUS Module Planner - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/se-edu/addressbook-level3

By: `CS2103T-W13-4`      Since: `Jan 2020`      Licence: `MIT`

== Introduction

NUS Module Planner (NUSModPlnr) is for those who prefer to use a desktop app to plan and manage their modules to fulfil their graduation requirements. More importantly, the NUSModPlnr optimized for those who prefer to work with a Command Line Interface (CLI) while still having the benefits of a Graphical User Interface (GUI). If you can type fast, NUSModPlnr can help you plan your modules in a fast, yet intuitive way.

== Quick Start

.  Ensure you have Java `11` or above installed in your Computer.
.  Download the latest `nusmodplnr.jar` link:{repoURL}/releases[here].
.  Copy the file to the folder you want to use as the home folder for your NUS Module Planner.
.  Double-click the file to start the app. The GUI should appear in a few seconds.
.  Type the command in the command box and press kbd:[Enter] to execute it. +
e.g. typing *`help`* and pressing kbd:[Enter] will open the help window.
.  Refer to Section 3, “Features” for details of each command.

[[Features]]
== Features

====
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `add n/NAME`, `NAME` is a parameter which can be used as `add n/John Doe`.
* Items in square brackets are optional e.g `n/NAME [t/TAG]` can be used as `n/John Doe t/friend` or as `n/John Doe`.
* Items with `…`​ after them can be used multiple times including zero times e.g. `[t/TAG]...` can be used as `{nbsp}` (i.e. 0 times), `t/friend`, `t/friend t/family` etc.
* Parameters can be in any order e.g. if the command specifies `n/NAME p/PHONE_NUMBER`, `p/PHONE_NUMBER n/NAME` is also acceptable.
====

=== Viewing help : `help`

Format: `help`

=== Declaring your major: `declare major`

Declares your major for studies and is required for the module planning. +
Format: `declare major [MAJOR]`

Examples:

* `declare major comsci`

=== Declaring your minor: `declare minor`

Declares your minor for studies. +
Format: `declare major [MINOR]`

Examples:

* `declare minor none`
* `declare minor comsci`

=== Declaring your specialisation: `declare spec`

Declares your Focus Areas, should you require them in module planning. +
Format: `declare spec [ACTION] [SPEC]`

Examples:

* `declare spec add networking`
* `declare spec remove networking`

=== Declaring your track: `declare track`

This is equivalent to `declare spec`.

=== Adding a module: `module add`

Add a module to your module list. +
Format: `module add [MODULE CODE]`

Examples:

* `module add CS2040`

=== Adding a module: `module remove`

Add a module to your module list. +
Format: `module remove [MODULE CODE]`

Examples:

* `module remove CS2040`

=== Viewing added modules: `module list`

Displays modules in your added module list. +
Format: `module list`

Examples:

* `module list`

=== Viewing exempted modules: `module list exempted`

Displays modules in your added module list. +
Format: `module list exempted`

Examples:

* `module list exempted`

=== Exiting the program : `exit`

Exits the program. +
Format: `exit`

=== Saving the data

NUS Module Planner data is saved to the hard disk automatically after any command that changes the data. +

There is no need to save manually.

// tag::sharingdatafiles[]
=== Sharing the data files `[coming in v2.0]`

_{explain how the user can enable/disable data encryption}_
// end::sharingdatafiles[]

== FAQ

*Q*: How do I transfer my data to another Computer? +
*A*: Install the app in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous NUSModPlnr folder.

== Command Summary

* *Help* : `help`
