= NUS Module Planner - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/se-edu/addressbook-level3

By: `CS2103T-W13-4`      Since: `Jan 2020`      Licence: `MIT`

== Introduction

NUS Module Planner (NUSModPlnr) is for those who prefer to use a desktop app to plan and manage their modules to fulfil their graduation requirements. More importantly, the NUSModPlnr optimized for those who prefer to work with a Command Line Interface (CLI) while still having the benefits of a Graphical User Interface (GUI). If you can type fast, NUSModPlnr can help you plan your modules in a fast, yet intuitive way.

== Quick Start

.  Ensure you have Java `11` or above installed in your Computer.
.  Download the latest `nusmodplnr.jar` link:{repoURL}/releases[here].
.  Copy the file to the folder you want to use as the home folder for your NUS Module Planner.
.  Double-click the file to start the app. The GUI should appear in a few seconds.
.  Type the command in the command box and press kbd:[Enter] to execute it. +
e.g. typing *`help`* and pressing kbd:[Enter] will open the help window.
.  Refer to Section 3, “Features” for details of each command.

[[Features]]
== Features

====
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `add n/NAME`, `NAME` is a parameter which can be used as `add n/John Doe`.
* Items in square brackets are optional e.g `n/NAME [t/TAG]` can be used as `n/John Doe t/friend` or as `n/John Doe`.
* Items with `…`​ after them can be used multiple times including zero times e.g. `[t/TAG]...` can be used as `{nbsp}` (i.e. 0 times), `t/friend`, `t/friend t/family` etc.
* Parameters can be in any order e.g. if the command specifies `n/NAME p/PHONE_NUMBER`, `p/PHONE_NUMBER n/NAME` is also acceptable.
====

====
*Common Parameters*

* `MODULE_CODE` - a code for a module in NUS
* `INDEX` - a index number of an item listed
** Must be a positive integer
* `NAME` - a name of a plan
** Must be alphanumeric, possibly with spaces
* `YEAR` - a year number
** Must be a non-negative integer
====

=== Viewing help : `help`

Format: `help`

=== Exiting the program : `exit`

Exits the program. +
Format: `exit`

=== Declaring your major: `declare major`

Declares your major for studies and is required for the module planning. +
Format: `declare major [MAJOR]`


Examples:

* `declare major comsci`

=== Declaring your minor: `declare minor`

Declares your minor for studies. +
Format: `declare major [MINOR]`

Examples:

* `declare minor none`
* `declare minor comsci`

=== Declaring your specialisation: `declare spec`

Declares your Focus Areas, should you require them in module planning. +
Format: `declare spec [ACTION] [SPEC]`

Examples:

* `declare spec add networking`
* `declare spec remove networking`

=== Declaring your track: `declare track`

This is equivalent to `declare spec`.

=== Adding a module: `module add`

Add a module to your timetable for the selected semester (see `timetable active`) and student (see `student active`). +
Format: `module add MODULE_CODE`
Example:

* `module add CS2040`

=== Removing a module: `module remove`

Remove a module from your timetable for the selected semester (see `timetable active`) and student (see `student active`). +
Format: `module remove MODULE_CODE`
Example:

* `module remove CS2040`

=== Viewing added modules: `module list`

Displays modules in your timetable for the selected semester (see `timetable active`) and student (see `student active`). +
Format: `module list`
Example:

* `module list`

=== Viewing exempted modules: `module list exempted`

Displays modules that you have declared as exempted.
Format: `module list exempted`
Example:

* `module list exempted`

=== View student list: `student list`

Displays a numbered list of students in the student list.
Format: `student list`
Example:

* `student list`

=== Add a student: `student add`

Adds a student to the student list.
Format: `student add n/NAME major/MAJOR`
Example:

* `student add n/Alice major/CS`

=== Remove a student: `student remove`

Removes the student with the number `INDEX` from the student list.
Format: `student remove INDEX`
Example:

* `student remove 1`

=== Select a student: `student active`

Selects the student with the number `INDEX` from the student list.
Format: `student active INDEX`
Example:

* `student active 1`

=== List timetables: `timetable list`

Lists the timetables of the selected student (see `student active`).
Format: `timetable list`
Example:

* `student list`

=== Add a timetable: `timetable add`

Adds a timetable to the specified semester of the selected student (see `student active`).
Format: `timetable add year/YEAR sem/SEM`
Example:

* `timetable add year/2 sem/ONE`

=== Remove a timetable: `timetable remove`

Removes the timetable for the specified semester and the selected student (see `student active`).
Format: `timetable remove year/YEAR sem/SEM`
Example:

* `timetable remove year/2 sem/ONE`

=== Select a timetable: `timetable active`

Selects the timetable for the specified semester and the selected student (see `student active`).
Format: `timetable active year/YEAR sem/SEM`
Example:

* `timetable active year/2 sem/ONE`

=== Saving the data

NUS Module Planner data is saved to the hard disk automatically after any command that changes the data. +

There is no need to save manually.

// tag::sharingdatafiles[]
=== Sharing the data files `[coming in v2.0]`

_{explain how the user can enable/disable data encryption}_
// end::sharingdatafiles[]

== FAQ

*Q*: How do I transfer my data to another Computer? +
*A*: Install the app in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous NUSModPlnr folder.

== Command Summary

* *Help* : `help`


